version: '3'

services:
 db:
  image: postgres
 controlpanel:
  build:
   context: .
  ports:
      - "8000:8000"
  depends_on:
    - db
  volumes:
  - ./controlpanel:/controlpanel
  command:
    sh -c "python manage.py runserver 0.0.0.0:8000"
